spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: l554725722@163.com #发送邮件的邮箱地址
    password: mbq1314520 #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: l554725722@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
  monitor:
    master.email: 554725722@qq.com #管理者邮箱
server:
  port: 8000

logging:
  config: classpath:logback-spring.xml


kafka:
  servers: 127.0.0.1:9092
  autoCommit: true
  autoCommitInterval: 1000
  sessionTimeOut: 30000
  autoOffsetReset: earliest
